# Generated by Django 4.1.3 on 2022-12-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Исполнитель')),
                ('content', models.TextField(blank=True, verbose_name='Информация')),
                ('photo', models.ImageField(db_column='photo', upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
    ]
